
# path_noisy_simulated_data= "/home/yanyang/data/em_dataset/simulated_particles/from_scipion/emd_6840/snr_0.1/"
# path_result_dir="formal_emd_6840_01_translate3_2022_2_10_test1"
# path_result_dir="/tmi_exp/emd_11669_005_with_preferred_orientations_2022_2_17_test1"
# path_result_dir="/tmi_exp/galactosidase_withoutP2_c75_2022_2_21_test1"
# path_result_dir="/home/yanyang/data/projects_resluts/vae_k_means/virus_2022_4_25_test1/"
# path_result_dir="/home/yanyang/data/projects_resluts/vae_k_means/Apoferritin_2022_4_26_test1/"
path_result_dir="/home/yanyang/data/projects_resluts/vae_k_means/6840_005_rand_cutout_2022_4_29_test1/"
# path_result_dir="formal_galactosidase_2022_1_21_test1"
# path_noisy_simulated_data= "/mnt/data_synology/yanyang/yanyang_data_backup/yanyang/em_dataset/real_particles/hbsag/"
# path_noisy_real_data= "/data/yanyang/em_dataset/real_particles/galactosidase/Movies/"
# path_noisy_real_data= "/mnt/data_synology/yanyang/yanyang_data_backup/yanyang/em_dataset/real_particles/hbsag/"
# path_noisy_real_data= "/mnt/data_synology/yanyang/data/em_dataset/real_particles/2021_particles_to_yanyang_part_10000/"
# path_noisy_real_data= "/mnt/data_synology/yanyang/data/em_dataset/real_particles/2021_virus_39000/P16_W27_particle_resized/"
# path_noisy_real_data= "/home/yanyang/data/em_dataset/simulated_particles/from_scipion/emd_6840/snr_0.1/"
# path_noisy_real_data= "/home/yanyang/data/em_dataset/simulated_particles/from_scipion/emd_6840/snr_0.1/"
# path_noisy_real_data= "/home/yanyang/data/em_dataset/real_particles/t20s_from_cryosparc/J170/extract/"
# path_noisy_real_data= "/home/yanyang/data/em_dataset/simulated_particles/with_translation/std3/emd_6840/snr_0.1/"
# path_noisy_real_data= "/home/yanyang/data/em_dataset/simulated_particles/with_translation/2022_new_dataset_with_preferred_orientations/emd_11669/snr_0.05/"
# path_noisy_real_data= "/home/yanyang/data/em_dataset/simulated_particles/with_translation/emd_6840/snr_0.1/"
# path_noisy_real_data= "/home/yanyang/data/em_dataset/real_particles/10034/"
# path_noisy_real_data= "/home/yanyang/data/em_dataset/real_particles/galactosidase/from_relion_extract/003784_ProtRelionExportParticles/Export/Particles/"
# path_noisy_real_data= "/home/yanyang/data/em_dataset/real_particles/galactosidase/from_my_relion_project_v3/job016/Movies/"
# path_data= "/home/yanyang/data/em_dataset/real_particles/P16_W27_particle/"
# path_data= "/home/yanyang/data/em_dataset/real_particles/Apoferritin240/"
# path_data= "/home/yanyang/data/em_dataset/simulated_particles/from_scipion/emd_6840/snr_0.05/"
# path_noisy_real_data= "/home/yanyang/data/em_dataset/real_particles/P16_W27_particle_resized/"
# path_for_data_classify="/home/yanyang/data/em_dataset/real_particles/10034/"
# path_for_data_classify="/home/yanyang/data/em_dataset/real_particles/galactosidase/from_relion_extract/003784_ProtRelionExportParticles/Export/Particles/"
# path_for_data_classify="/home/yanyang/data/em_dataset/real_particles/galactosidase/from_my_relion_project_v3/job016/Movies/"
# path_for_data_classify="/home/yanyang/data/em_dataset/simulated_particles/with_translation/2022_new_dataset_translate_0/emd_5001/snr_0.05/"
# path_for_data_classify="/home/yanyang/data/em_dataset/simulated_particles/with_translation/std3/emd_6840/snr_0.1/"
# path_for_data_classify= "/home/yanyang/data/em_dataset/simulated_particles/with_translation/2022_new_dataset_with_preferred_orientations/emd_11669/snr_0.05/"
# path_for_data_classify="/home/yanyang/data/em_dataset/real_particles/P16_W27_particle/"
# path_for_data_classify="/home/yanyang/data/em_dataset/simulated_particles/from_scipion/emd_6840/snr_0.1/"
# path_noisy_real_data= "/mnt/data_synology/yanyang/yanyang_data_backup/yanyang/em_dataset/simulated_particles/from_scipion/emd_6840/snr_0.1/"
# path_noisy_real_data= "/data/yanyang/em_dataset/real_particles/10034/"
# path_noisy_real_data= "/home/yanyang/data/em_dataset/real_particles/10034/"
# path_noisy_real_data= "/home/yanyang/data/em_dataset/real_particles/galactosidase/Movies/"
# path_noisy_real_data="/data/yanyang/em_dataset/simulated_particles/from_scipion/emd_5001/snr_0.1/"
is_save_clustered_single_particles=True
resized_mrc_width = 128
resized_mrc_height = 128
crop_ratio=0.8
# all_mrc_pixels = 16384
var=0.2
training_in_phase_2=False
clustering_interval=1
# cluster_num = 10
# cluster_num=100
# clustering_size = 360
# rotate_times = 180
# final_rotate_times = 360
max_iteration_times = 25
# num_random_select = 10
using_circle_features=True

read_from_path=True
is_simulated_dataset=True
num_threads = 6 # influence features extraction
circle_features_num=31
circle_feature_length=2

# epoches_round1 = 31#emd_5001
# epoches_round2 = 5#emd_5001
# epoches_round1 = 121#emd_6840
# epoches_round2 = 10#emd_6840
# epoches_round1 = 50#emd_6840
# epoches_round2 = 91#emd_6840
# epoches_round1 = 800#emd_11669
# epoches_round2 = 300#emd_11669
# epoches_round1 = 800#real_6840
# epoches_round2 = 10#real_6840
# epoches_round1 = 56#emd_10034
# epoches_round2 = 3#emd_10034
# epoches_round1 = 26#emd_10035
# epoches_round2 = 10#emd_10035
epoches_round1 = 180#galactosidase
# epoches_round1 = 180#galactosidase
# epoches_round2 = 3#galactosidase
# epoches_round1 = 180#t20s
epoches_round2 = 5#t20s
# epoches_round1 = 966 #hbsag
# epoches_round2 = 10#hbsag
# epoches_round1 = 266 #virus
# epoches_round1 = 266 #virus
# epoches_round2 = 2#virus
# epoches_round1 = 3#test
# epoches_round2 = 3#test