path_result_dir: /home/yanyang/data/projects_resluts/vae_k_means/tmi_v3/emd_5001/emd_5001_01_without_shift_ctf_4/
path_data: /home/yanyang/data/em_dataset/simulated_particles/with_translation/2022_new_dataset_translate_0/emd_5001/without_shift_ctf/j176_5001_01_01/sub_mrcs/
old_proj_path: /home/yanyang/data/projects_resluts/vae_k_means/hbsag_vae_2022_6_21_test2/


epoches_round1: 100
epoches_round2: 10
batch_size: 40
cluster_num: 10
is_simulated_dataset: 1
start_from_old_model: 0
using_mas: 0
kmeans_mode: 1


# Transformations
augmentation_strategy: cryoEM_v1

augmentation_kwargs:
   phase 1:
      is_random_rotate: 1
   #   random_resized_crop:
   #      size: 128
   #      scale: [0.9, 1.0]
   #      ratio: [0.95,1.05]
      is_Normalize: 1
#      cutout_kwargs:
#         p: 0.4
#         value: [-3,3]
#      random_pixel_lost:
#         p: 0.5
#         ratio: 0.5
   phase 2:
      is_random_rotate: 1
#      random_resized_crop:
#         size: 128
#         scale: [0.9, 1.0]
#         ratio: [0.95,1.05]
      is_Normalize: 1
   #   cutout_kwargs:
   #      p: 0.4
   #      value: [-3,3]
#      random_pixel_lost:
#         p: 0.6
#         ratio: 0.5

# Preprocess
preprocess_kwargs:
#   crop_ratio: 1
   resize: 128